### ISSUE TITLE
안녕하세요! 

### ISSUE THREAD

**Issue by ChoiHyeongu** [chungchung21/chungchung21.github.io#1]
민트기술 이충경님 맞으신가요??

**Comment by chungchung21** [comment]
ㅎㅎㅎ 네 형우님~
잘 있어요?
군대 갔어요?

**Comment by ChoiHyeongu** [comment]
앗 아니요 ㅋㅋㅋㅋㅋㅋ 충경님 혹시 전화 가능하실까요? 지금 있는 곳에서 전회사 근로소득원천징수영수증를 받아야하는데 연락할만한 수단이 없어서 허허... 가능하시면 01022691061로 전화주세요!

**Comment by ChoiHyeongu** [comment]
전화번호 때문에 제 코멘트는 삭제하겠습니다!
